name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.7.0
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Lint Addon
        run: pnpm run lint:js
        working-directory: packages/ember-runtime-config

      - name: Lint Test App
        run: pnpm run lint:js
        working-directory: packages/test-app

      - name: Run Tests
        run: pnpm run test:ember
        working-directory: packages/test-app

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.7.0
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i --no-lockfile

      - name: Run Tests
        run: pnpm run test:ember
        working-directory: packages/test-app

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    needs: "test"
    env:
      GREETING: "Hello, world!"

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-3.28
          - ember-lts-4.4
          - ember-lts-4.8
          - ember-lts-4.12
          - ember-release
          - ember-beta
          - ember-canary
          - embroider-safe
          - embroider-optimized

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.7.0
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Run Tests
        run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
        working-directory: packages/test-app

  types:
    name: type tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ts-version:
          - 5.0
          - next

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.7.0
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Install TypeScript
        run: pnpm add -D typescript@${{ matrix.ts-version }}
        working-directory: packages/ember-runtime-config

      - name: Compile TypeScript
        run: tsc --noEmit
        working-directory: packages/ember-runtime-config

    continue-on-error: ${{ matrix.ts-version == 'next' }}
