name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Run Tests
        run: yarn test:ember

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --no-lockfile

      - name: Run Tests
        run: yarn test:ember

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    needs: "test"
    env:
      GREETING: "Hello, world!"

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-3.24
          - ember-lts-3.28
          - ember-lts-4.4
          - ember-release
          - ember-beta
          - ember-canary
          - ember-classic
          - embroider-safe
          - embroider-optimized

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}

  types:
    name: type tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ts-version:
          - 4.4
          - 4.5
          - 4.6
          - 4.7
          - 4.8
          - next

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Install TypeScript
        run: yarn add -D typescript@${{ matrix.ts-version }}

      - name: Compile TypeScript
        run: tsc --noEmit

    continue-on-error: ${{ matrix.ts-version == 'next' }}
